# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.8"
    architecture: "x64"
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.9"
    architecture: "x64"
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.10"
    architecture: "x64"
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.11"
    architecture: "x64"
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.12"
    architecture: "x64"

- script: |
    curl -sSf -o rustup-init.exe https://win.rustup.rs
    rustup-init.exe -y --profile minimal --default-host x86_64-pc-windows-msvc
    set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  displayName: "Install Rust toolchain"

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
