blank_issues_enabled: true
contact_links:
  - name: Read the documentation
    url: https://docs.astral.sh/uv
    about: Please consult the documentation before creating an issue.
  - name: Join the community
    url: https://discord.com/invite/astral-sh
    about: Join our Discord community to ask questions and collaborate.
